language: cpp
compiler: gcc
sudo: false
addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - g++-4.8
      - clang
      - libgtest-dev

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -

script:
    - ls -al
    - make CXX=clang++ GOOGLETEST=~/gtest
    - make test